### ISSUE TITLE
一压缩就崩溃了

### ISSUE THREAD

**Issue by dajiba666** [zerochl/FFMPEG-AAC-264-Android-32-64#1]

**Comment by zerochl** [comment]
此压缩程序依赖与视频与音频的格式，H264+AAC没有问题，音频不支持AMR

**Comment by daniel-wuhj** [comment]
华为mate9手机，压缩就会崩溃，

**Comment by zerochl** [comment]
demo的录制兼容有问题，建议自行录制，压缩请注意视频与音频格式，如果视频有特殊要求可以按照提供的shell文件自行选择视频与音频格式
